### ISSUE TITLE
Crashing server with steam-Sven Coop when installing metamod-r

### ISSUE THREAD

**Issue by Manapo74** [theAsmodai/metamod-r#29] opened 2018-02-03 08:02 UTC
Please help, REHLDS is not working and not search game dll :(

**Comment by stamepicmorg** [comment] 2018-02-05 19:54
hmm. do u mean metamod-r or rehlds?

anyway.. strange. write a name of game dll please and version of svencoop. i will try to reproduce it.

or check filename with this [file](https://github.com/theAsmodai/metamod-r/blob/master/metamod/src/game_support.cpp) manually.

**Comment by stamepicmorg** [comment] 2018-02-16 11:25
@Manapo74 ?

**Comment by Manapo74** [comment] 2018-03-02 05:27
Sorry, I did not see the notification. I am install metamod-r for sven coop but it not working.
I see this error: "failure to init extension dl; exiting..."
- Windows 10
- Protocol version 48
Exe version 5.0.0.0 (svencoop)
Exe build: 19:07:22 Dec 23 2017 (7730)
- local game
- server.dll

**Comment by stamepicmorg** [comment] 2018-03-03 21:59
thank u. i will try to reproduce it.

**Comment by Manapo74** [comment] 2018-03-07 21:33
Not working :c
"failure to init extension dl; exiting..."

**Comment by stamepicmorg** [comment] 2018-03-09 16:55
> Not working :c

@Manapo74 tommorow (2018/03/10) i will try to reprpduce it. sorry for my long testing, at this week i havent free time :(

**Comment by stamepicmorg** [comment] 2018-03-10 11:42
@Manapo74, I catched and partially confirmed your problem. 

but this bug it does not apply directly to the svencoop - it's global bug in metamod-r. i think, soon it will be fixed. temporrary closing this issue.

**Comment by Manapo74** [comment] 2018-03-10 13:19
Hello, thanks. But ReHLDS is not working on svencoop :( 
---------
I am get this error:
![image](https://user-images.githubusercontent.com/34998786/37242681-89c5da6a-24a8-11e8-8ef2-97188b70a6f3.png)
---------
Start.bat:
hlds.exe -game svencoop -port 27015 +maxplayers 32 +sv_lan 0 +map hl_c01_a1

**Comment by stamepicmorg** [comment] 2018-03-10 14:39
> ReHLDS is not working on svencoop
we know. sad but  true. https://github.com/theAsmodai/metamod-r/issues/17

rehlds is working. but only with maps that are not have oveloaded limit of precache.  if u load map as crossfire - all be ok. i test it. this 512-limit - is engine's limit. if u play network-based maps all be ok. 'cause they are created with it. but standalone-based maps has other limit - 1024 or more (i forget). and if u try to load singleplayer or other ovelimited map on (any type server: original or rehlds) - u catch this error too. but svenccop has modiffed limits (i dont know how) from 512 to 1024 or more for play singleplayer-based maps at multiplayer.. i think u can ask rehlds team to add more perecahe limit to rehlds. it will be awesome.

but. metamod-r working correctly only with rehlds. and have no guaranties that metamod-r will be stable with stock-hlds (6xxx or 7xxx). I tested it and can show this table:

#### Running metamod-r with some enviromets

game| hlds 6xxx| hlds 7xxx| rehlds
------|------|-----------|------
Half-Life 1 | 👍 | 👍| 👍
SvenCoop 5.x | 👎  | 👎| 👍

**Comment by stamepicmorg** [comment] 2018-03-11 19:52
@Manapo74 hi there 👍 i saw u issue at rehlds-repo and answer.. maby [this](https://forums.alliedmods.net/showthread.php?t=200826) workaround can resolve problem too.

**Comment by Manapo74** [comment] 2018-03-11 23:23
Hello, thanks. But, i am wait update for Metamod-r :)
Can you please tell me when will the new "release" come about?

**Comment by theAsmodai** [comment] 2018-03-12 00:15
Released https://github.com/theAsmodai/metamod-r/releases/tag/1.3.119

**Comment by Manapo74** [comment] 2018-03-12 07:52
Error again :(
"Failure to init extension DLL; exiting..."

**Comment by stamepicmorg** [comment] 2018-03-12 09:45
> Error again :(

Because metamod-r **requeres** rehlds installed. And rehlds are not really usable with SvenCoop.

**Comment by Manapo74** [comment] 2018-03-12 23:29
This metamod unstable:
https://github.com/jonnyboy0719/MetaMod-P/tree/unstable

On some maps this metamode works unstably, server ping jumps up to 300-700.
For example: 
hl_c03 - ping 250-400
hl_c04 - ping server at the end of the map 200-260

**Comment by stamepicmorg** [comment] 2018-10-03 22:43
@Manapo74 hello! problem resolved [here](https://github.com/theAsmodai/metamod-r/issues/45).

**Comment by stamepicmorg** [comment] 2018-10-03 22:50
@Manapo74 hello! problem resolved [here](https://github.com/theAsmodai/metamod-r/issues/45).

**Closed by stamepicmorg** 2018-10-03 22:50 UTC
Labels: OS: Windows, Priority: Medium, Status: Pending, Type: Bug, Type: Help wanted
